syntax = "proto3";

package metaserver;

option go_package = "github.com/umangshikarvar/dvfs/api/metaserver";

message UserACL {
  string username = 1;
  repeated string shared = 2; // users who have access to this user's root
}

message RegisterFileServerRequest {
  string address = 1;
  repeated string users = 2;
  repeated UserACL acls = 3; // ACL information for each user
}

message RegisterFileServerResponse {
  bool success = 1;
  string error = 2;
}

message NavigateRequest {
  string username = 1;
  string root_user = 2;
}

message NavigateResponse {
  bool success = 1;
  string error = 2;
  string address = 3; // address of the file server to connect to
}

message GetRootsRequest {
  string username = 1;
}

message GetRootsResponse {
  bool success = 1;
  string error = 2;
  repeated string roots = 3;
}

message RootShareRequest {
  string root_user = 1;
  string share_with = 2;
}

message RootShareResponse {
  bool success = 1;
  string error = 2;
}

message RootUnshareRequest {
  string root_user = 1;
  string unshare_with = 2;
}

message RootUnshareResponse {
  bool success = 1;
  string error = 2;
}

message HeartbeatRequest {
  string address = 1;
}

message HeartbeatResponse {
  bool success = 1;
  string error = 2;
}

// MetaServer service
service MetaServer {
  rpc RegisterFileServer(RegisterFileServerRequest) returns (RegisterFileServerResponse);
  rpc Navigate(NavigateRequest) returns (NavigateResponse);
  rpc Heartbeat(HeartbeatRequest) returns (HeartbeatResponse);
  rpc GetRoots(GetRootsRequest) returns (GetRootsResponse);
  rpc RootShare(RootShareRequest) returns (RootShareResponse);
  rpc RootUnshare(RootUnshareRequest) returns (RootUnshareResponse);
}