// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/metaserver/metaserver.proto

package metaserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SharedDir struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`   // Full path including username (e.g., "/umang", "/umang/proj")
	Users         []string               `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"` // Users with explicit access to this directory
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Owner         string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SharedDir) Reset() {
	*x = SharedDir{}
	mi := &file_api_metaserver_metaserver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SharedDir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedDir) ProtoMessage() {}

func (x *SharedDir) ProtoReflect() protoreflect.Message {
	mi := &file_api_metaserver_metaserver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharedDir.ProtoReflect.Descriptor instead.
func (*SharedDir) Descriptor() ([]byte, []int) {
	return file_api_metaserver_metaserver_proto_rawDescGZIP(), []int{0}
}

func (x *SharedDir) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SharedDir) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *SharedDir) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SharedDir) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type SharedRoot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Owner         string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SharedRoot) Reset() {
	*x = SharedRoot{}
	mi := &file_api_metaserver_metaserver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SharedRoot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedRoot) ProtoMessage() {}

func (x *SharedRoot) ProtoReflect() protoreflect.Message {
	mi := &file_api_metaserver_metaserver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharedRoot.ProtoReflect.Descriptor instead.
func (*SharedRoot) Descriptor() ([]byte, []int) {
	return file_api_metaserver_metaserver_proto_rawDescGZIP(), []int{1}
}

func (x *SharedRoot) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SharedRoot) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *SharedRoot) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type RegisterFileServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Users         []string               `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Shared        []*SharedDir           `protobuf:"bytes,3,rep,name=shared,proto3" json:"shared,omitempty"` // ACL information for each user
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterFileServerRequest) Reset() {
	*x = RegisterFileServerRequest{}
	mi := &file_api_metaserver_metaserver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterFileServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterFileServerRequest) ProtoMessage() {}

func (x *RegisterFileServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_metaserver_metaserver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterFileServerRequest.ProtoReflect.Descriptor instead.
func (*RegisterFileServerRequest) Descriptor() ([]byte, []int) {
	return file_api_metaserver_metaserver_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterFileServerRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterFileServerRequest) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *RegisterFileServerRequest) GetShared() []*SharedDir {
	if x != nil {
		return x.Shared
	}
	return nil
}

type RegisterFileServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterFileServerResponse) Reset() {
	*x = RegisterFileServerResponse{}
	mi := &file_api_metaserver_metaserver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterFileServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterFileServerResponse) ProtoMessage() {}

func (x *RegisterFileServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_metaserver_metaserver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterFileServerResponse.ProtoReflect.Descriptor instead.
func (*RegisterFileServerResponse) Descriptor() ([]byte, []int) {
	return file_api_metaserver_metaserver_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterFileServerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterFileServerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type NavigateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	RootUser      string                 `protobuf:"bytes,2,opt,name=root_user,json=rootUser,proto3" json:"root_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NavigateRequest) Reset() {
	*x = NavigateRequest{}
	mi := &file_api_metaserver_metaserver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NavigateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavigateRequest) ProtoMessage() {}

func (x *NavigateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_metaserver_metaserver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavigateRequest.ProtoReflect.Descriptor instead.
func (*NavigateRequest) Descriptor() ([]byte, []int) {
	return file_api_metaserver_metaserver_proto_rawDescGZIP(), []int{4}
}

func (x *NavigateRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *NavigateRequest) GetRootUser() string {
	if x != nil {
		return x.RootUser
	}
	return ""
}

type NavigateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"` // address of the file server to connect to
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NavigateResponse) Reset() {
	*x = NavigateResponse{}
	mi := &file_api_metaserver_metaserver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NavigateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavigateResponse) ProtoMessage() {}

func (x *NavigateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_metaserver_metaserver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavigateResponse.ProtoReflect.Descriptor instead.
func (*NavigateResponse) Descriptor() ([]byte, []int) {
	return file_api_metaserver_metaserver_proto_rawDescGZIP(), []int{5}
}

func (x *NavigateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NavigateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *NavigateResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetRootsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRootsRequest) Reset() {
	*x = GetRootsRequest{}
	mi := &file_api_metaserver_metaserver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRootsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRootsRequest) ProtoMessage() {}

func (x *GetRootsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_metaserver_metaserver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRootsRequest.ProtoReflect.Descriptor instead.
func (*GetRootsRequest) Descriptor() ([]byte, []int) {
	return file_api_metaserver_metaserver_proto_rawDescGZIP(), []int{6}
}

func (x *GetRootsRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetRootsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Roots         []*SharedRoot          `protobuf:"bytes,3,rep,name=roots,proto3" json:"roots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRootsResponse) Reset() {
	*x = GetRootsResponse{}
	mi := &file_api_metaserver_metaserver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRootsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRootsResponse) ProtoMessage() {}

func (x *GetRootsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_metaserver_metaserver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRootsResponse.ProtoReflect.Descriptor instead.
func (*GetRootsResponse) Descriptor() ([]byte, []int) {
	return file_api_metaserver_metaserver_proto_rawDescGZIP(), []int{7}
}

func (x *GetRootsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetRootsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetRootsResponse) GetRoots() []*SharedRoot {
	if x != nil {
		return x.Roots
	}
	return nil
}

type RootShareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootPath      string                 `protobuf:"bytes,1,opt,name=root_path,json=rootPath,proto3" json:"root_path,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	ShareWith     string                 `protobuf:"bytes,3,opt,name=share_with,json=shareWith,proto3" json:"share_with,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootShareRequest) Reset() {
	*x = RootShareRequest{}
	mi := &file_api_metaserver_metaserver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootShareRequest) ProtoMessage() {}

func (x *RootShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_metaserver_metaserver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootShareRequest.ProtoReflect.Descriptor instead.
func (*RootShareRequest) Descriptor() ([]byte, []int) {
	return file_api_metaserver_metaserver_proto_rawDescGZIP(), []int{8}
}

func (x *RootShareRequest) GetRootPath() string {
	if x != nil {
		return x.RootPath
	}
	return ""
}

func (x *RootShareRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *RootShareRequest) GetShareWith() string {
	if x != nil {
		return x.ShareWith
	}
	return ""
}

func (x *RootShareRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RootShareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootShareResponse) Reset() {
	*x = RootShareResponse{}
	mi := &file_api_metaserver_metaserver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootShareResponse) ProtoMessage() {}

func (x *RootShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_metaserver_metaserver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootShareResponse.ProtoReflect.Descriptor instead.
func (*RootShareResponse) Descriptor() ([]byte, []int) {
	return file_api_metaserver_metaserver_proto_rawDescGZIP(), []int{9}
}

func (x *RootShareResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RootShareResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RootUnshareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootPath      string                 `protobuf:"bytes,1,opt,name=root_path,json=rootPath,proto3" json:"root_path,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	UnshareWith   string                 `protobuf:"bytes,3,opt,name=unshare_with,json=unshareWith,proto3" json:"unshare_with,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootUnshareRequest) Reset() {
	*x = RootUnshareRequest{}
	mi := &file_api_metaserver_metaserver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootUnshareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootUnshareRequest) ProtoMessage() {}

func (x *RootUnshareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_metaserver_metaserver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootUnshareRequest.ProtoReflect.Descriptor instead.
func (*RootUnshareRequest) Descriptor() ([]byte, []int) {
	return file_api_metaserver_metaserver_proto_rawDescGZIP(), []int{10}
}

func (x *RootUnshareRequest) GetRootPath() string {
	if x != nil {
		return x.RootPath
	}
	return ""
}

func (x *RootUnshareRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *RootUnshareRequest) GetUnshareWith() string {
	if x != nil {
		return x.UnshareWith
	}
	return ""
}

func (x *RootUnshareRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RootUnshareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootUnshareResponse) Reset() {
	*x = RootUnshareResponse{}
	mi := &file_api_metaserver_metaserver_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootUnshareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootUnshareResponse) ProtoMessage() {}

func (x *RootUnshareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_metaserver_metaserver_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootUnshareResponse.ProtoReflect.Descriptor instead.
func (*RootUnshareResponse) Descriptor() ([]byte, []int) {
	return file_api_metaserver_metaserver_proto_rawDescGZIP(), []int{11}
}

func (x *RootUnshareResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RootUnshareResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_metaserver_metaserver_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_metaserver_metaserver_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_metaserver_metaserver_proto_rawDescGZIP(), []int{12}
}

func (x *HeartbeatRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_metaserver_metaserver_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_metaserver_metaserver_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_metaserver_metaserver_proto_rawDescGZIP(), []int{13}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_metaserver_metaserver_proto protoreflect.FileDescriptor

const file_api_metaserver_metaserver_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/metaserver/metaserver.proto\x12\n" +
	"metaserver\"_\n" +
	"\tSharedDir\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05users\x18\x02 \x03(\tR\x05users\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\"Y\n" +
	"\n" +
	"SharedRoot\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\"z\n" +
	"\x19RegisterFileServerRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x14\n" +
	"\x05users\x18\x02 \x03(\tR\x05users\x12-\n" +
	"\x06shared\x18\x03 \x03(\v2\x15.metaserver.SharedDirR\x06shared\"L\n" +
	"\x1aRegisterFileServerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"J\n" +
	"\x0fNavigateRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1b\n" +
	"\troot_user\x18\x02 \x01(\tR\brootUser\"\\\n" +
	"\x10NavigateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"-\n" +
	"\x0fGetRootsRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"p\n" +
	"\x10GetRootsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12,\n" +
	"\x05roots\x18\x03 \x03(\v2\x16.metaserver.SharedRootR\x05roots\"x\n" +
	"\x10RootShareRequest\x12\x1b\n" +
	"\troot_path\x18\x01 \x01(\tR\brootPath\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12\x1d\n" +
	"\n" +
	"share_with\x18\x03 \x01(\tR\tshareWith\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"C\n" +
	"\x11RootShareResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"~\n" +
	"\x12RootUnshareRequest\x12\x1b\n" +
	"\troot_path\x18\x01 \x01(\tR\brootPath\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12!\n" +
	"\funshare_with\x18\x03 \x01(\tR\vunshareWith\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"E\n" +
	"\x13RootUnshareResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\",\n" +
	"\x10HeartbeatRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"C\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xe3\x03\n" +
	"\n" +
	"MetaServer\x12c\n" +
	"\x12RegisterFileServer\x12%.metaserver.RegisterFileServerRequest\x1a&.metaserver.RegisterFileServerResponse\x12E\n" +
	"\bNavigate\x12\x1b.metaserver.NavigateRequest\x1a\x1c.metaserver.NavigateResponse\x12H\n" +
	"\tHeartbeat\x12\x1c.metaserver.HeartbeatRequest\x1a\x1d.metaserver.HeartbeatResponse\x12E\n" +
	"\bGetRoots\x12\x1b.metaserver.GetRootsRequest\x1a\x1c.metaserver.GetRootsResponse\x12H\n" +
	"\tRootShare\x12\x1c.metaserver.RootShareRequest\x1a\x1d.metaserver.RootShareResponse\x12N\n" +
	"\vRootUnshare\x12\x1e.metaserver.RootUnshareRequest\x1a\x1f.metaserver.RootUnshareResponseB/Z-github.com/umangshikarvar/dvfs/api/metaserverb\x06proto3"

var (
	file_api_metaserver_metaserver_proto_rawDescOnce sync.Once
	file_api_metaserver_metaserver_proto_rawDescData []byte
)

func file_api_metaserver_metaserver_proto_rawDescGZIP() []byte {
	file_api_metaserver_metaserver_proto_rawDescOnce.Do(func() {
		file_api_metaserver_metaserver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_metaserver_metaserver_proto_rawDesc), len(file_api_metaserver_metaserver_proto_rawDesc)))
	})
	return file_api_metaserver_metaserver_proto_rawDescData
}

var file_api_metaserver_metaserver_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_metaserver_metaserver_proto_goTypes = []any{
	(*SharedDir)(nil),                  // 0: metaserver.SharedDir
	(*SharedRoot)(nil),                 // 1: metaserver.SharedRoot
	(*RegisterFileServerRequest)(nil),  // 2: metaserver.RegisterFileServerRequest
	(*RegisterFileServerResponse)(nil), // 3: metaserver.RegisterFileServerResponse
	(*NavigateRequest)(nil),            // 4: metaserver.NavigateRequest
	(*NavigateResponse)(nil),           // 5: metaserver.NavigateResponse
	(*GetRootsRequest)(nil),            // 6: metaserver.GetRootsRequest
	(*GetRootsResponse)(nil),           // 7: metaserver.GetRootsResponse
	(*RootShareRequest)(nil),           // 8: metaserver.RootShareRequest
	(*RootShareResponse)(nil),          // 9: metaserver.RootShareResponse
	(*RootUnshareRequest)(nil),         // 10: metaserver.RootUnshareRequest
	(*RootUnshareResponse)(nil),        // 11: metaserver.RootUnshareResponse
	(*HeartbeatRequest)(nil),           // 12: metaserver.HeartbeatRequest
	(*HeartbeatResponse)(nil),          // 13: metaserver.HeartbeatResponse
}
var file_api_metaserver_metaserver_proto_depIdxs = []int32{
	0,  // 0: metaserver.RegisterFileServerRequest.shared:type_name -> metaserver.SharedDir
	1,  // 1: metaserver.GetRootsResponse.roots:type_name -> metaserver.SharedRoot
	2,  // 2: metaserver.MetaServer.RegisterFileServer:input_type -> metaserver.RegisterFileServerRequest
	4,  // 3: metaserver.MetaServer.Navigate:input_type -> metaserver.NavigateRequest
	12, // 4: metaserver.MetaServer.Heartbeat:input_type -> metaserver.HeartbeatRequest
	6,  // 5: metaserver.MetaServer.GetRoots:input_type -> metaserver.GetRootsRequest
	8,  // 6: metaserver.MetaServer.RootShare:input_type -> metaserver.RootShareRequest
	10, // 7: metaserver.MetaServer.RootUnshare:input_type -> metaserver.RootUnshareRequest
	3,  // 8: metaserver.MetaServer.RegisterFileServer:output_type -> metaserver.RegisterFileServerResponse
	5,  // 9: metaserver.MetaServer.Navigate:output_type -> metaserver.NavigateResponse
	13, // 10: metaserver.MetaServer.Heartbeat:output_type -> metaserver.HeartbeatResponse
	7,  // 11: metaserver.MetaServer.GetRoots:output_type -> metaserver.GetRootsResponse
	9,  // 12: metaserver.MetaServer.RootShare:output_type -> metaserver.RootShareResponse
	11, // 13: metaserver.MetaServer.RootUnshare:output_type -> metaserver.RootUnshareResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_metaserver_metaserver_proto_init() }
func file_api_metaserver_metaserver_proto_init() {
	if File_api_metaserver_metaserver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_metaserver_metaserver_proto_rawDesc), len(file_api_metaserver_metaserver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_metaserver_metaserver_proto_goTypes,
		DependencyIndexes: file_api_metaserver_metaserver_proto_depIdxs,
		MessageInfos:      file_api_metaserver_metaserver_proto_msgTypes,
	}.Build()
	File_api_metaserver_metaserver_proto = out.File
	file_api_metaserver_metaserver_proto_goTypes = nil
	file_api_metaserver_metaserver_proto_depIdxs = nil
}
