// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: api/metaserver/metaserver.proto

package metaserver

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetaServer_RegisterFileServer_FullMethodName = "/metaserver.MetaServer/RegisterFileServer"
	MetaServer_Navigate_FullMethodName           = "/metaserver.MetaServer/Navigate"
	MetaServer_GetRoots_FullMethodName           = "/metaserver.MetaServer/GetRoots"
)

// MetaServerClient is the client API for MetaServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MetaServer service
type MetaServerClient interface {
	RegisterFileServer(ctx context.Context, in *RegisterFileServerRequest, opts ...grpc.CallOption) (*RegisterFileServerResponse, error)
	Navigate(ctx context.Context, in *NavigateRequest, opts ...grpc.CallOption) (*NavigateResponse, error)
	GetRoots(ctx context.Context, in *GetRootsRequest, opts ...grpc.CallOption) (*GetRootsResponse, error)
}

type metaServerClient struct {
	cc grpc.ClientConnInterface
}

func NewMetaServerClient(cc grpc.ClientConnInterface) MetaServerClient {
	return &metaServerClient{cc}
}

func (c *metaServerClient) RegisterFileServer(ctx context.Context, in *RegisterFileServerRequest, opts ...grpc.CallOption) (*RegisterFileServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterFileServerResponse)
	err := c.cc.Invoke(ctx, MetaServer_RegisterFileServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaServerClient) Navigate(ctx context.Context, in *NavigateRequest, opts ...grpc.CallOption) (*NavigateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NavigateResponse)
	err := c.cc.Invoke(ctx, MetaServer_Navigate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaServerClient) GetRoots(ctx context.Context, in *GetRootsRequest, opts ...grpc.CallOption) (*GetRootsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRootsResponse)
	err := c.cc.Invoke(ctx, MetaServer_GetRoots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetaServerServer is the server API for MetaServer service.
// All implementations must embed UnimplementedMetaServerServer
// for forward compatibility.
//
// MetaServer service
type MetaServerServer interface {
	RegisterFileServer(context.Context, *RegisterFileServerRequest) (*RegisterFileServerResponse, error)
	Navigate(context.Context, *NavigateRequest) (*NavigateResponse, error)
	GetRoots(context.Context, *GetRootsRequest) (*GetRootsResponse, error)
	mustEmbedUnimplementedMetaServerServer()
}

// UnimplementedMetaServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetaServerServer struct{}

func (UnimplementedMetaServerServer) RegisterFileServer(context.Context, *RegisterFileServerRequest) (*RegisterFileServerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterFileServer not implemented")
}
func (UnimplementedMetaServerServer) Navigate(context.Context, *NavigateRequest) (*NavigateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Navigate not implemented")
}
func (UnimplementedMetaServerServer) GetRoots(context.Context, *GetRootsRequest) (*GetRootsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoots not implemented")
}
func (UnimplementedMetaServerServer) mustEmbedUnimplementedMetaServerServer() {}
func (UnimplementedMetaServerServer) testEmbeddedByValue()                    {}

// UnsafeMetaServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetaServerServer will
// result in compilation errors.
type UnsafeMetaServerServer interface {
	mustEmbedUnimplementedMetaServerServer()
}

func RegisterMetaServerServer(s grpc.ServiceRegistrar, srv MetaServerServer) {
	// If the following call panics, it indicates UnimplementedMetaServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetaServer_ServiceDesc, srv)
}

func _MetaServer_RegisterFileServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterFileServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServerServer).RegisterFileServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaServer_RegisterFileServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServerServer).RegisterFileServer(ctx, req.(*RegisterFileServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaServer_Navigate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NavigateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServerServer).Navigate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaServer_Navigate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServerServer).Navigate(ctx, req.(*NavigateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaServer_GetRoots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRootsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServerServer).GetRoots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaServer_GetRoots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServerServer).GetRoots(ctx, req.(*GetRootsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetaServer_ServiceDesc is the grpc.ServiceDesc for MetaServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetaServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metaserver.MetaServer",
	HandlerType: (*MetaServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterFileServer",
			Handler:    _MetaServer_RegisterFileServer_Handler,
		},
		{
			MethodName: "Navigate",
			Handler:    _MetaServer_Navigate_Handler,
		},
		{
			MethodName: "GetRoots",
			Handler:    _MetaServer_GetRoots_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/metaserver/metaserver.proto",
}
