syntax = "proto3";

package metaserver;

option go_package = "github.com/umangshikarvar/dvfs/api/metaserver";

message RegisterFileServerRequest {
  string address = 1;
  repeated string users = 2;
}

message RegisterFileServerResponse {
  bool success = 1;
  string error = 2;
}

message NavigateRequest {
  string user = 2;
}

message NavigateResponse {
  bool success = 1;
  string error = 2;
  string file_server = 3; // address of the file server to connect to
}

// MetaServer service
service MetaServer {
  rpc RegisterFileServer(RegisterFileServerRequest) returns (RegisterFileServerResponse);
  rpc Navigate(NavigateRequest) returns (NavigateResponse);
}