package client

import (
	"crypto/x509"
	"fmt"
)

// RootCAPEM contains the public certificate of the 10-year offline DVFS Root CA.
// Embedded directly into the client binary; no external ca_cert file required.
const RootCAPEM = `-----BEGIN CERTIFICATE-----
MIIF6jCCA9KgAwIBAgIQRMVQ5lcrYnBauUgotMP6ZzANBgkqhkiG9w0BAQsFADB+
MQswCQYDVQQGEwJJTjEQMA4GA1UECBMHR3VqYXJhdDEUMBIGA1UEBxMLR2FuZGhp
bmFnYXIxFTATBgNVBAoTDERWRlMgUHJvamVjdDERMA8GA1UECxMIU2VjdXJpdHkx
HTAbBgNVBAMTFERWRlMgT2ZmbGluZSBSb290IENBMB4XDTI2MDkwNzA0NDIyN1oX
DTM2MDkwNjA0NDIyN1owfjELMAkGA1UEBhMCSU4xEDAOBgNVBAgTB0d1amFyYXQx
FDASBgNVBAcTC0dhbmRoaW5hZ2FyMRUwEwYDVQQKEwxEVkZTIFByb2plY3QxETAP
BgNVBAsTCFNlY3VyaXR5MR0wGwYDVQQDExREVkZTIE9mZmxpbmUgUm9vdCBDQTCC
AiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAKhRlIbTY25KD0JmkPquQ2Wy
ro1IQXCOqdi7vom7QIkbGn/o85DPEArR8vU8QonEzdj9tYBeSi/2FrG+aBAtN2sM
JHWgJJcNTgYvH8HTwCSMwQUIAWsnqMn4NFUr/w0WSRz2PBzr9hDS9qoHPy7C652K
dGSM8IFYStVLIBrKfOJ7JKwrxhde9tAdWpyDksVtt2Lcrxn5M+ub8/eb7jHG3tZ0
tTMnR6zHZvIATIDkp8EVouq1kvzed4U4i7FBANMKJUqp1crKpThZMBt3gIjDzKpC
G23kF6Xjc2KMdTSDjY0TTnlrfxdi13kpHrVn07yG0wIu/AIZU6GkNFXQAc5t1seL
cvPKbIzigjXmyO9xLI10r47GxPrNGao0y8tSH8KKTomBjte8EYekvpCZnX35Sn/f
PYPqB/IwTmsoj2OopFT0lZNhf3BUPCbnx8rdD4NKpnGoeUajtv+J/37pqbX1reBY
xB4U9VtIc84ULSkW0Ms4Bm6AnisFGuqVCFOlHJ7i5NF+xR9a/MnmDwcEq22VSvyU
a85yKiO1enbpLg7Ue6jhiTJokU4U+Jax3pYZFLW0imCA1oSYZQtS0lmQHNV4d05u
6Ht/0+VpTAilhr4HjlUuWAhWI0EdJhKc10/RvWQCG4+/qkrHVrGve4EP1nX50u8g
aFi0MKoyRqu05cEVxf21AgMBAAGjZDBiMA4GA1UdDwEB/wQEAwIBhjAdBgNVHSUE
FjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwEgYDVR0TAQH/BAgwBgEB/wIBATAdBgNV
HQ4EFgQUb3BjU/6cqZDLQo8XOdlLTiLPQ5UwDQYJKoZIhvcNAQELBQADggIBAKVK
w/EXft4Z1i0NJGRoQkotiLbEY4LT+/RsSCcQfUHk1JQeM3jIs29aWAahuzDg4oWF
MDUI5EAO+ywu9SZgW6XHYtOgAeG8a47K97WqfYa8cooRNR1yn1g9xh2z1x7r4ZCf
umYb2m0s/CiZjfwnjxJnxuc01yZ7R7jhamClMKkVS/7d/q6v5dJi4jBn2mlp3SZg
ioj9nrKbCjo8P9ESvOHI3Fz5VaOXWKK87Tj/yDUHxhYxhWqdiQSc/9gkrPw2N4cV
xwiJtIYGUSXeZK+XVUuKw/DxPy2MJKmEGGdWh/+y+n1gSlGLIvuE08ii7J45uJaa
x7QWU+ts3L8aRrQaWSPEZqCja6FewwkkTP/w/6ydH1s2lwhIKnDQdfj2sEAzRIFe
kpYk/6KaTbbpEfQmY6nTXwDAwYy4gEszkARbrbQwgxuJbgrStEyDCMbAnBqxC/eQ
NkGKJtmzc9JeZW9LvTBDNpfUGYzmAPL4m0cGyrAXfzA88RmOO/HbK+DnozrEBwKm
Dq06QcPlr/zqVFo1qKNd8tT0dOys20axF3YqyGqEbaIFdtsHR9QYuOoYxNRsQVWN
LaD427tH2Lw6XCeLXsrCC4JngL4M4gnVLo8znqjEZNWLDYVC4xpq8JWpm7G3JIcw
cVPyxI268y43qC5y/e0Y+2AFH9rlyfBQB4Y/i0+O
-----END CERTIFICATE-----`

// NewDVFSUniversalCertPool creates an isolated x509.CertPool containing strictly
// the DVFS Root CA, completely ignoring the host operating system's root store.
// It uses the embedded RootCAPEM and also incorporates any local certs/ca.crt if found.
func NewDVFSUniversalCertPool() (*x509.CertPool, error) {
	pool := x509.NewCertPool()
	if !pool.AppendCertsFromPEM([]byte(RootCAPEM)) {
		return nil, fmt.Errorf("failed to append hardcoded DVFS Root CA certificate")
	}
	return pool, nil
}
