// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/fileserver/fileserver.proto

package fileserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// File/Directory Type
type InodeType int32

const (
	InodeType_FILE      InodeType = 0
	InodeType_DIRECTORY InodeType = 1
)

// Enum value maps for InodeType.
var (
	InodeType_name = map[int32]string{
		0: "FILE",
		1: "DIRECTORY",
	}
	InodeType_value = map[string]int32{
		"FILE":      0,
		"DIRECTORY": 1,
	}
)

func (x InodeType) Enum() *InodeType {
	p := new(InodeType)
	*p = x
	return p
}

func (x InodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_fileserver_fileserver_proto_enumTypes[0].Descriptor()
}

func (InodeType) Type() protoreflect.EnumType {
	return &file_api_fileserver_fileserver_proto_enumTypes[0]
}

func (x InodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InodeType.Descriptor instead.
func (InodeType) EnumDescriptor() ([]byte, []int) {
	return file_api_fileserver_fileserver_proto_rawDescGZIP(), []int{0}
}

// File Identifier
type FID struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FileServerId     string                 `protobuf:"bytes,1,opt,name=file_server_id,json=fileServerId,proto3" json:"file_server_id,omitempty"`
	InodeId          uint64                 `protobuf:"varint,2,opt,name=inode_id,json=inodeId,proto3" json:"inode_id,omitempty"`
	GenerationNumber uint64                 `protobuf:"varint,3,opt,name=generation_number,json=generationNumber,proto3" json:"generation_number,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FID) Reset() {
	*x = FID{}
	mi := &file_api_fileserver_fileserver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FID) ProtoMessage() {}

func (x *FID) ProtoReflect() protoreflect.Message {
	mi := &file_api_fileserver_fileserver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FID.ProtoReflect.Descriptor instead.
func (*FID) Descriptor() ([]byte, []int) {
	return file_api_fileserver_fileserver_proto_rawDescGZIP(), []int{0}
}

func (x *FID) GetFileServerId() string {
	if x != nil {
		return x.FileServerId
	}
	return ""
}

func (x *FID) GetInodeId() uint64 {
	if x != nil {
		return x.InodeId
	}
	return 0
}

func (x *FID) GetGenerationNumber() uint64 {
	if x != nil {
		return x.GenerationNumber
	}
	return 0
}

// Access Control List
type ACL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReadUsers     []string               `protobuf:"bytes,1,rep,name=read_users,json=readUsers,proto3" json:"read_users,omitempty"`
	WriteUsers    []string               `protobuf:"bytes,2,rep,name=write_users,json=writeUsers,proto3" json:"write_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ACL) Reset() {
	*x = ACL{}
	mi := &file_api_fileserver_fileserver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ACL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACL) ProtoMessage() {}

func (x *ACL) ProtoReflect() protoreflect.Message {
	mi := &file_api_fileserver_fileserver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACL.ProtoReflect.Descriptor instead.
func (*ACL) Descriptor() ([]byte, []int) {
	return file_api_fileserver_fileserver_proto_rawDescGZIP(), []int{1}
}

func (x *ACL) GetReadUsers() []string {
	if x != nil {
		return x.ReadUsers
	}
	return nil
}

func (x *ACL) GetWriteUsers() []string {
	if x != nil {
		return x.WriteUsers
	}
	return nil
}

// === File Operations ===
type PathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fid           *FID                   `protobuf:"bytes,1,opt,name=fid,proto3" json:"fid,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathRequest) Reset() {
	*x = PathRequest{}
	mi := &file_api_fileserver_fileserver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathRequest) ProtoMessage() {}

func (x *PathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_fileserver_fileserver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathRequest.ProtoReflect.Descriptor instead.
func (*PathRequest) Descriptor() ([]byte, []int) {
	return file_api_fileserver_fileserver_proto_rawDescGZIP(), []int{2}
}

func (x *PathRequest) GetFid() *FID {
	if x != nil {
		return x.Fid
	}
	return nil
}

func (x *PathRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type PathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathResponse) Reset() {
	*x = PathResponse{}
	mi := &file_api_fileserver_fileserver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathResponse) ProtoMessage() {}

func (x *PathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_fileserver_fileserver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathResponse.ProtoReflect.Descriptor instead.
func (*PathResponse) Descriptor() ([]byte, []int) {
	return file_api_fileserver_fileserver_proto_rawDescGZIP(), []int{3}
}

func (x *PathResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PathResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PathResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CreateFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentPath    string                 `protobuf:"bytes,1,opt,name=parent_path,json=parentPath,proto3" json:"parent_path,omitempty"` // path on server
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Type          InodeType              `protobuf:"varint,4,opt,name=type,proto3,enum=fileserver.InodeType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileRequest) Reset() {
	*x = CreateFileRequest{}
	mi := &file_api_fileserver_fileserver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileRequest) ProtoMessage() {}

func (x *CreateFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_fileserver_fileserver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileRequest.ProtoReflect.Descriptor instead.
func (*CreateFileRequest) Descriptor() ([]byte, []int) {
	return file_api_fileserver_fileserver_proto_rawDescGZIP(), []int{4}
}

func (x *CreateFileRequest) GetParentPath() string {
	if x != nil {
		return x.ParentPath
	}
	return ""
}

func (x *CreateFileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateFileRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *CreateFileRequest) GetType() InodeType {
	if x != nil {
		return x.Type
	}
	return InodeType_FILE
}

type CreateFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fid           *FID                   `protobuf:"bytes,1,opt,name=fid,proto3" json:"fid,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileResponse) Reset() {
	*x = CreateFileResponse{}
	mi := &file_api_fileserver_fileserver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileResponse) ProtoMessage() {}

func (x *CreateFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_fileserver_fileserver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileResponse.ProtoReflect.Descriptor instead.
func (*CreateFileResponse) Descriptor() ([]byte, []int) {
	return file_api_fileserver_fileserver_proto_rawDescGZIP(), []int{5}
}

func (x *CreateFileResponse) GetFid() *FID {
	if x != nil {
		return x.Fid
	}
	return nil
}

func (x *CreateFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateFileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type OpenFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fid           *FID                   `protobuf:"bytes,1,opt,name=fid,proto3" json:"fid,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	ClientId      string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // for callbacks
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenFileRequest) Reset() {
	*x = OpenFileRequest{}
	mi := &file_api_fileserver_fileserver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenFileRequest) ProtoMessage() {}

func (x *OpenFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_fileserver_fileserver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenFileRequest.ProtoReflect.Descriptor instead.
func (*OpenFileRequest) Descriptor() ([]byte, []int) {
	return file_api_fileserver_fileserver_proto_rawDescGZIP(), []int{6}
}

func (x *OpenFileRequest) GetFid() *FID {
	if x != nil {
		return x.Fid
	}
	return nil
}

func (x *OpenFileRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *OpenFileRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type OpenFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	FileSize      uint64                 `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Version       uint64                 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"` // for cache validation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenFileResponse) Reset() {
	*x = OpenFileResponse{}
	mi := &file_api_fileserver_fileserver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenFileResponse) ProtoMessage() {}

func (x *OpenFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_fileserver_fileserver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenFileResponse.ProtoReflect.Descriptor instead.
func (*OpenFileResponse) Descriptor() ([]byte, []int) {
	return file_api_fileserver_fileserver_proto_rawDescGZIP(), []int{7}
}

func (x *OpenFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OpenFileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *OpenFileResponse) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *OpenFileResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ReadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fid           *FID                   `protobuf:"bytes,1,opt,name=fid,proto3" json:"fid,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        uint64                 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	User          string                 `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_api_fileserver_fileserver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_fileserver_fileserver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_api_fileserver_fileserver_proto_rawDescGZIP(), []int{8}
}

func (x *ReadFileRequest) GetFid() *FID {
	if x != nil {
		return x.Fid
	}
	return nil
}

func (x *ReadFileRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadFileRequest) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *ReadFileRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type ReadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileResponse) Reset() {
	*x = ReadFileResponse{}
	mi := &file_api_fileserver_fileserver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResponse) ProtoMessage() {}

func (x *ReadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_fileserver_fileserver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResponse.ProtoReflect.Descriptor instead.
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return file_api_fileserver_fileserver_proto_rawDescGZIP(), []int{9}
}

func (x *ReadFileResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReadFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReadFileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type WriteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fid           *FID                   `protobuf:"bytes,1,opt,name=fid,proto3" json:"fid,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	User          string                 `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	ClientId      string                 `protobuf:"bytes,5,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_api_fileserver_fileserver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_fileserver_fileserver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_api_fileserver_fileserver_proto_rawDescGZIP(), []int{10}
}

func (x *WriteFileRequest) GetFid() *FID {
	if x != nil {
		return x.Fid
	}
	return nil
}

func (x *WriteFileRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *WriteFileRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WriteFileRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *WriteFileRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type WriteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Version       uint64                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"` // new version after write
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileResponse) Reset() {
	*x = WriteFileResponse{}
	mi := &file_api_fileserver_fileserver_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileResponse) ProtoMessage() {}

func (x *WriteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_fileserver_fileserver_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileResponse.ProtoReflect.Descriptor instead.
func (*WriteFileResponse) Descriptor() ([]byte, []int) {
	return file_api_fileserver_fileserver_proto_rawDescGZIP(), []int{11}
}

func (x *WriteFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WriteFileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *WriteFileResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type CloseFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fid           *FID                   `protobuf:"bytes,1,opt,name=fid,proto3" json:"fid,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	ClientId      string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseFileRequest) Reset() {
	*x = CloseFileRequest{}
	mi := &file_api_fileserver_fileserver_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseFileRequest) ProtoMessage() {}

func (x *CloseFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_fileserver_fileserver_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseFileRequest.ProtoReflect.Descriptor instead.
func (*CloseFileRequest) Descriptor() ([]byte, []int) {
	return file_api_fileserver_fileserver_proto_rawDescGZIP(), []int{12}
}

func (x *CloseFileRequest) GetFid() *FID {
	if x != nil {
		return x.Fid
	}
	return nil
}

func (x *CloseFileRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *CloseFileRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type CloseFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseFileResponse) Reset() {
	*x = CloseFileResponse{}
	mi := &file_api_fileserver_fileserver_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseFileResponse) ProtoMessage() {}

func (x *CloseFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_fileserver_fileserver_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseFileResponse.ProtoReflect.Descriptor instead.
func (*CloseFileResponse) Descriptor() ([]byte, []int) {
	return file_api_fileserver_fileserver_proto_rawDescGZIP(), []int{13}
}

func (x *CloseFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CloseFileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fid           *FID                   `protobuf:"bytes,1,opt,name=fid,proto3" json:"fid,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_api_fileserver_fileserver_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_fileserver_fileserver_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_api_fileserver_fileserver_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteFileRequest) GetFid() *FID {
	if x != nil {
		return x.Fid
	}
	return nil
}

func (x *DeleteFileRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type DeleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	mi := &file_api_fileserver_fileserver_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_fileserver_fileserver_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_api_fileserver_fileserver_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteFileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetAttrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fid           *FID                   `protobuf:"bytes,1,opt,name=fid,proto3" json:"fid,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttrRequest) Reset() {
	*x = GetAttrRequest{}
	mi := &file_api_fileserver_fileserver_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttrRequest) ProtoMessage() {}

func (x *GetAttrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_fileserver_fileserver_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttrRequest.ProtoReflect.Descriptor instead.
func (*GetAttrRequest) Descriptor() ([]byte, []int) {
	return file_api_fileserver_fileserver_proto_rawDescGZIP(), []int{16}
}

func (x *GetAttrRequest) GetFid() *FID {
	if x != nil {
		return x.Fid
	}
	return nil
}

func (x *GetAttrRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type GetAttrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type          InodeType              `protobuf:"varint,4,opt,name=type,proto3,enum=fileserver.InodeType" json:"type,omitempty"`
	Size          uint64                 `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Version       uint64                 `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttrResponse) Reset() {
	*x = GetAttrResponse{}
	mi := &file_api_fileserver_fileserver_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttrResponse) ProtoMessage() {}

func (x *GetAttrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_fileserver_fileserver_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttrResponse.ProtoReflect.Descriptor instead.
func (*GetAttrResponse) Descriptor() ([]byte, []int) {
	return file_api_fileserver_fileserver_proto_rawDescGZIP(), []int{17}
}

func (x *GetAttrResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetAttrResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetAttrResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetAttrResponse) GetType() InodeType {
	if x != nil {
		return x.Type
	}
	return InodeType_FILE
}

func (x *GetAttrResponse) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetAttrResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ListDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fid           *FID                   `protobuf:"bytes,1,opt,name=fid,proto3" json:"fid,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirRequest) Reset() {
	*x = ListDirRequest{}
	mi := &file_api_fileserver_fileserver_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirRequest) ProtoMessage() {}

func (x *ListDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_fileserver_fileserver_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirRequest.ProtoReflect.Descriptor instead.
func (*ListDirRequest) Descriptor() ([]byte, []int) {
	return file_api_fileserver_fileserver_proto_rawDescGZIP(), []int{18}
}

func (x *ListDirRequest) GetFid() *FID {
	if x != nil {
		return x.Fid
	}
	return nil
}

func (x *ListDirRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type DirEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fid           *FID                   `protobuf:"bytes,1,opt,name=fid,proto3" json:"fid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          InodeType              `protobuf:"varint,3,opt,name=type,proto3,enum=fileserver.InodeType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirEntry) Reset() {
	*x = DirEntry{}
	mi := &file_api_fileserver_fileserver_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirEntry) ProtoMessage() {}

func (x *DirEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_fileserver_fileserver_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirEntry.ProtoReflect.Descriptor instead.
func (*DirEntry) Descriptor() ([]byte, []int) {
	return file_api_fileserver_fileserver_proto_rawDescGZIP(), []int{19}
}

func (x *DirEntry) GetFid() *FID {
	if x != nil {
		return x.Fid
	}
	return nil
}

func (x *DirEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DirEntry) GetType() InodeType {
	if x != nil {
		return x.Type
	}
	return InodeType_FILE
}

type ListDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Entries       []*DirEntry            `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirResponse) Reset() {
	*x = ListDirResponse{}
	mi := &file_api_fileserver_fileserver_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirResponse) ProtoMessage() {}

func (x *ListDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_fileserver_fileserver_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirResponse.ProtoReflect.Descriptor instead.
func (*ListDirResponse) Descriptor() ([]byte, []int) {
	return file_api_fileserver_fileserver_proto_rawDescGZIP(), []int{20}
}

func (x *ListDirResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListDirResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ListDirResponse) GetEntries() []*DirEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type LookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentFid     *FID                   `protobuf:"bytes,1,opt,name=parent_fid,json=parentFid,proto3" json:"parent_fid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupRequest) Reset() {
	*x = LookupRequest{}
	mi := &file_api_fileserver_fileserver_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupRequest) ProtoMessage() {}

func (x *LookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_fileserver_fileserver_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupRequest.ProtoReflect.Descriptor instead.
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return file_api_fileserver_fileserver_proto_rawDescGZIP(), []int{21}
}

func (x *LookupRequest) GetParentFid() *FID {
	if x != nil {
		return x.ParentFid
	}
	return nil
}

func (x *LookupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LookupRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type LookupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Fid           *FID                   `protobuf:"bytes,3,opt,name=fid,proto3" json:"fid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupResponse) Reset() {
	*x = LookupResponse{}
	mi := &file_api_fileserver_fileserver_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupResponse) ProtoMessage() {}

func (x *LookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_fileserver_fileserver_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupResponse.ProtoReflect.Descriptor instead.
func (*LookupResponse) Descriptor() ([]byte, []int) {
	return file_api_fileserver_fileserver_proto_rawDescGZIP(), []int{22}
}

func (x *LookupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LookupResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *LookupResponse) GetFid() *FID {
	if x != nil {
		return x.Fid
	}
	return nil
}

type RegisterClientRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClientId        string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	CallbackAddress string                 `protobuf:"bytes,2,opt,name=callback_address,json=callbackAddress,proto3" json:"callback_address,omitempty"` // host:port for callbacks
	Username        string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`                                      // user's name for creating user directory
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterClientRequest) Reset() {
	*x = RegisterClientRequest{}
	mi := &file_api_fileserver_fileserver_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterClientRequest) ProtoMessage() {}

func (x *RegisterClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_fileserver_fileserver_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterClientRequest.ProtoReflect.Descriptor instead.
func (*RegisterClientRequest) Descriptor() ([]byte, []int) {
	return file_api_fileserver_fileserver_proto_rawDescGZIP(), []int{23}
}

func (x *RegisterClientRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RegisterClientRequest) GetCallbackAddress() string {
	if x != nil {
		return x.CallbackAddress
	}
	return ""
}

func (x *RegisterClientRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type RegisterClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	UserRootFid   *FID                   `protobuf:"bytes,3,opt,name=user_root_fid,json=userRootFid,proto3" json:"user_root_fid,omitempty"` // FID of user's root directory
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterClientResponse) Reset() {
	*x = RegisterClientResponse{}
	mi := &file_api_fileserver_fileserver_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterClientResponse) ProtoMessage() {}

func (x *RegisterClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_fileserver_fileserver_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterClientResponse.ProtoReflect.Descriptor instead.
func (*RegisterClientResponse) Descriptor() ([]byte, []int) {
	return file_api_fileserver_fileserver_proto_rawDescGZIP(), []int{24}
}

func (x *RegisterClientResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterClientResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RegisterClientResponse) GetUserRootFid() *FID {
	if x != nil {
		return x.UserRootFid
	}
	return nil
}

var File_api_fileserver_fileserver_proto protoreflect.FileDescriptor

const file_api_fileserver_fileserver_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/fileserver/fileserver.proto\x12\n" +
	"fileserver\"s\n" +
	"\x03FID\x12$\n" +
	"\x0efile_server_id\x18\x01 \x01(\tR\ffileServerId\x12\x19\n" +
	"\binode_id\x18\x02 \x01(\x04R\ainodeId\x12+\n" +
	"\x11generation_number\x18\x03 \x01(\x04R\x10generationNumber\"E\n" +
	"\x03ACL\x12\x1d\n" +
	"\n" +
	"read_users\x18\x01 \x03(\tR\treadUsers\x12\x1f\n" +
	"\vwrite_users\x18\x02 \x03(\tR\n" +
	"writeUsers\"D\n" +
	"\vPathRequest\x12!\n" +
	"\x03fid\x18\x01 \x01(\v2\x0f.fileserver.FIDR\x03fid\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\"R\n" +
	"\fPathResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x87\x01\n" +
	"\x11CreateFileRequest\x12\x1f\n" +
	"\vparent_path\x18\x01 \x01(\tR\n" +
	"parentPath\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12)\n" +
	"\x04type\x18\x04 \x01(\x0e2\x15.fileserver.InodeTypeR\x04type\"g\n" +
	"\x12CreateFileResponse\x12!\n" +
	"\x03fid\x18\x01 \x01(\v2\x0f.fileserver.FIDR\x03fid\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"e\n" +
	"\x0fOpenFileRequest\x12!\n" +
	"\x03fid\x18\x01 \x01(\v2\x0f.fileserver.FIDR\x03fid\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\"y\n" +
	"\x10OpenFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1b\n" +
	"\tfile_size\x18\x03 \x01(\x04R\bfileSize\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x04R\aversion\"x\n" +
	"\x0fReadFileRequest\x12!\n" +
	"\x03fid\x18\x01 \x01(\v2\x0f.fileserver.FIDR\x03fid\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x04R\x06length\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04user\"V\n" +
	"\x10ReadFileResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x92\x01\n" +
	"\x10WriteFileRequest\x12!\n" +
	"\x03fid\x18\x01 \x01(\v2\x0f.fileserver.FIDR\x03fid\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04user\x12\x1b\n" +
	"\tclient_id\x18\x05 \x01(\tR\bclientId\"]\n" +
	"\x11WriteFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\"f\n" +
	"\x10CloseFileRequest\x12!\n" +
	"\x03fid\x18\x01 \x01(\v2\x0f.fileserver.FIDR\x03fid\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\"C\n" +
	"\x11CloseFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"J\n" +
	"\x11DeleteFileRequest\x12!\n" +
	"\x03fid\x18\x01 \x01(\v2\x0f.fileserver.FIDR\x03fid\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\"D\n" +
	"\x12DeleteFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"G\n" +
	"\x0eGetAttrRequest\x12!\n" +
	"\x03fid\x18\x01 \x01(\v2\x0f.fileserver.FIDR\x03fid\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\"\xae\x01\n" +
	"\x0fGetAttrResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12)\n" +
	"\x04type\x18\x04 \x01(\x0e2\x15.fileserver.InodeTypeR\x04type\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x04R\x04size\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x04R\aversion\"G\n" +
	"\x0eListDirRequest\x12!\n" +
	"\x03fid\x18\x01 \x01(\v2\x0f.fileserver.FIDR\x03fid\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\"l\n" +
	"\bDirEntry\x12!\n" +
	"\x03fid\x18\x01 \x01(\v2\x0f.fileserver.FIDR\x03fid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12)\n" +
	"\x04type\x18\x03 \x01(\x0e2\x15.fileserver.InodeTypeR\x04type\"q\n" +
	"\x0fListDirResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12.\n" +
	"\aentries\x18\x03 \x03(\v2\x14.fileserver.DirEntryR\aentries\"g\n" +
	"\rLookupRequest\x12.\n" +
	"\n" +
	"parent_fid\x18\x01 \x01(\v2\x0f.fileserver.FIDR\tparentFid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\"c\n" +
	"\x0eLookupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12!\n" +
	"\x03fid\x18\x03 \x01(\v2\x0f.fileserver.FIDR\x03fid\"{\n" +
	"\x15RegisterClientRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12)\n" +
	"\x10callback_address\x18\x02 \x01(\tR\x0fcallbackAddress\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\"}\n" +
	"\x16RegisterClientResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x123\n" +
	"\ruser_root_fid\x18\x03 \x01(\v2\x0f.fileserver.FIDR\vuserRootFid*$\n" +
	"\tInodeType\x12\b\n" +
	"\x04FILE\x10\x00\x12\r\n" +
	"\tDIRECTORY\x10\x012\xa5\x06\n" +
	"\n" +
	"FileServer\x12W\n" +
	"\x0eRegisterClient\x12!.fileserver.RegisterClientRequest\x1a\".fileserver.RegisterClientResponse\x12K\n" +
	"\n" +
	"CreateFile\x12\x1d.fileserver.CreateFileRequest\x1a\x1e.fileserver.CreateFileResponse\x12E\n" +
	"\bOpenFile\x12\x1b.fileserver.OpenFileRequest\x1a\x1c.fileserver.OpenFileResponse\x12E\n" +
	"\bReadFile\x12\x1b.fileserver.ReadFileRequest\x1a\x1c.fileserver.ReadFileResponse\x12H\n" +
	"\tWriteFile\x12\x1c.fileserver.WriteFileRequest\x1a\x1d.fileserver.WriteFileResponse\x12H\n" +
	"\tCloseFile\x12\x1c.fileserver.CloseFileRequest\x1a\x1d.fileserver.CloseFileResponse\x12K\n" +
	"\n" +
	"DeleteFile\x12\x1d.fileserver.DeleteFileRequest\x1a\x1e.fileserver.DeleteFileResponse\x12B\n" +
	"\aGetAttr\x12\x1a.fileserver.GetAttrRequest\x1a\x1b.fileserver.GetAttrResponse\x12B\n" +
	"\aListDir\x12\x1a.fileserver.ListDirRequest\x1a\x1b.fileserver.ListDirResponse\x12?\n" +
	"\x06Lookup\x12\x19.fileserver.LookupRequest\x1a\x1a.fileserver.LookupResponse\x129\n" +
	"\x04Path\x12\x17.fileserver.PathRequest\x1a\x18.fileserver.PathResponseB/Z-github.com/umangshikarvar/dvfs/api/fileserverb\x06proto3"

var (
	file_api_fileserver_fileserver_proto_rawDescOnce sync.Once
	file_api_fileserver_fileserver_proto_rawDescData []byte
)

func file_api_fileserver_fileserver_proto_rawDescGZIP() []byte {
	file_api_fileserver_fileserver_proto_rawDescOnce.Do(func() {
		file_api_fileserver_fileserver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_fileserver_fileserver_proto_rawDesc), len(file_api_fileserver_fileserver_proto_rawDesc)))
	})
	return file_api_fileserver_fileserver_proto_rawDescData
}

var file_api_fileserver_fileserver_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_fileserver_fileserver_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_api_fileserver_fileserver_proto_goTypes = []any{
	(InodeType)(0),                 // 0: fileserver.InodeType
	(*FID)(nil),                    // 1: fileserver.FID
	(*ACL)(nil),                    // 2: fileserver.ACL
	(*PathRequest)(nil),            // 3: fileserver.PathRequest
	(*PathResponse)(nil),           // 4: fileserver.PathResponse
	(*CreateFileRequest)(nil),      // 5: fileserver.CreateFileRequest
	(*CreateFileResponse)(nil),     // 6: fileserver.CreateFileResponse
	(*OpenFileRequest)(nil),        // 7: fileserver.OpenFileRequest
	(*OpenFileResponse)(nil),       // 8: fileserver.OpenFileResponse
	(*ReadFileRequest)(nil),        // 9: fileserver.ReadFileRequest
	(*ReadFileResponse)(nil),       // 10: fileserver.ReadFileResponse
	(*WriteFileRequest)(nil),       // 11: fileserver.WriteFileRequest
	(*WriteFileResponse)(nil),      // 12: fileserver.WriteFileResponse
	(*CloseFileRequest)(nil),       // 13: fileserver.CloseFileRequest
	(*CloseFileResponse)(nil),      // 14: fileserver.CloseFileResponse
	(*DeleteFileRequest)(nil),      // 15: fileserver.DeleteFileRequest
	(*DeleteFileResponse)(nil),     // 16: fileserver.DeleteFileResponse
	(*GetAttrRequest)(nil),         // 17: fileserver.GetAttrRequest
	(*GetAttrResponse)(nil),        // 18: fileserver.GetAttrResponse
	(*ListDirRequest)(nil),         // 19: fileserver.ListDirRequest
	(*DirEntry)(nil),               // 20: fileserver.DirEntry
	(*ListDirResponse)(nil),        // 21: fileserver.ListDirResponse
	(*LookupRequest)(nil),          // 22: fileserver.LookupRequest
	(*LookupResponse)(nil),         // 23: fileserver.LookupResponse
	(*RegisterClientRequest)(nil),  // 24: fileserver.RegisterClientRequest
	(*RegisterClientResponse)(nil), // 25: fileserver.RegisterClientResponse
}
var file_api_fileserver_fileserver_proto_depIdxs = []int32{
	1,  // 0: fileserver.PathRequest.fid:type_name -> fileserver.FID
	0,  // 1: fileserver.CreateFileRequest.type:type_name -> fileserver.InodeType
	1,  // 2: fileserver.CreateFileResponse.fid:type_name -> fileserver.FID
	1,  // 3: fileserver.OpenFileRequest.fid:type_name -> fileserver.FID
	1,  // 4: fileserver.ReadFileRequest.fid:type_name -> fileserver.FID
	1,  // 5: fileserver.WriteFileRequest.fid:type_name -> fileserver.FID
	1,  // 6: fileserver.CloseFileRequest.fid:type_name -> fileserver.FID
	1,  // 7: fileserver.DeleteFileRequest.fid:type_name -> fileserver.FID
	1,  // 8: fileserver.GetAttrRequest.fid:type_name -> fileserver.FID
	0,  // 9: fileserver.GetAttrResponse.type:type_name -> fileserver.InodeType
	1,  // 10: fileserver.ListDirRequest.fid:type_name -> fileserver.FID
	1,  // 11: fileserver.DirEntry.fid:type_name -> fileserver.FID
	0,  // 12: fileserver.DirEntry.type:type_name -> fileserver.InodeType
	20, // 13: fileserver.ListDirResponse.entries:type_name -> fileserver.DirEntry
	1,  // 14: fileserver.LookupRequest.parent_fid:type_name -> fileserver.FID
	1,  // 15: fileserver.LookupResponse.fid:type_name -> fileserver.FID
	1,  // 16: fileserver.RegisterClientResponse.user_root_fid:type_name -> fileserver.FID
	24, // 17: fileserver.FileServer.RegisterClient:input_type -> fileserver.RegisterClientRequest
	5,  // 18: fileserver.FileServer.CreateFile:input_type -> fileserver.CreateFileRequest
	7,  // 19: fileserver.FileServer.OpenFile:input_type -> fileserver.OpenFileRequest
	9,  // 20: fileserver.FileServer.ReadFile:input_type -> fileserver.ReadFileRequest
	11, // 21: fileserver.FileServer.WriteFile:input_type -> fileserver.WriteFileRequest
	13, // 22: fileserver.FileServer.CloseFile:input_type -> fileserver.CloseFileRequest
	15, // 23: fileserver.FileServer.DeleteFile:input_type -> fileserver.DeleteFileRequest
	17, // 24: fileserver.FileServer.GetAttr:input_type -> fileserver.GetAttrRequest
	19, // 25: fileserver.FileServer.ListDir:input_type -> fileserver.ListDirRequest
	22, // 26: fileserver.FileServer.Lookup:input_type -> fileserver.LookupRequest
	3,  // 27: fileserver.FileServer.Path:input_type -> fileserver.PathRequest
	25, // 28: fileserver.FileServer.RegisterClient:output_type -> fileserver.RegisterClientResponse
	6,  // 29: fileserver.FileServer.CreateFile:output_type -> fileserver.CreateFileResponse
	8,  // 30: fileserver.FileServer.OpenFile:output_type -> fileserver.OpenFileResponse
	10, // 31: fileserver.FileServer.ReadFile:output_type -> fileserver.ReadFileResponse
	12, // 32: fileserver.FileServer.WriteFile:output_type -> fileserver.WriteFileResponse
	14, // 33: fileserver.FileServer.CloseFile:output_type -> fileserver.CloseFileResponse
	16, // 34: fileserver.FileServer.DeleteFile:output_type -> fileserver.DeleteFileResponse
	18, // 35: fileserver.FileServer.GetAttr:output_type -> fileserver.GetAttrResponse
	21, // 36: fileserver.FileServer.ListDir:output_type -> fileserver.ListDirResponse
	23, // 37: fileserver.FileServer.Lookup:output_type -> fileserver.LookupResponse
	4,  // 38: fileserver.FileServer.Path:output_type -> fileserver.PathResponse
	28, // [28:39] is the sub-list for method output_type
	17, // [17:28] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_api_fileserver_fileserver_proto_init() }
func file_api_fileserver_fileserver_proto_init() {
	if File_api_fileserver_fileserver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_fileserver_fileserver_proto_rawDesc), len(file_api_fileserver_fileserver_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_fileserver_fileserver_proto_goTypes,
		DependencyIndexes: file_api_fileserver_fileserver_proto_depIdxs,
		EnumInfos:         file_api_fileserver_fileserver_proto_enumTypes,
		MessageInfos:      file_api_fileserver_fileserver_proto_msgTypes,
	}.Build()
	File_api_fileserver_fileserver_proto = out.File
	file_api_fileserver_fileserver_proto_goTypes = nil
	file_api_fileserver_fileserver_proto_depIdxs = nil
}
