// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/callback/callback.proto

package callback

import (
	fileserver "github.com/umangshikarvar/dvfs/api/fileserver"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Callback messages for cache invalidation
type InvalidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fid           *fileserver.FID        `protobuf:"bytes,1,opt,name=fid,proto3" json:"fid,omitempty"`
	NewVersion    uint64                 `protobuf:"varint,2,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidateRequest) Reset() {
	*x = InvalidateRequest{}
	mi := &file_api_callback_callback_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateRequest) ProtoMessage() {}

func (x *InvalidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_callback_callback_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateRequest.ProtoReflect.Descriptor instead.
func (*InvalidateRequest) Descriptor() ([]byte, []int) {
	return file_api_callback_callback_proto_rawDescGZIP(), []int{0}
}

func (x *InvalidateRequest) GetFid() *fileserver.FID {
	if x != nil {
		return x.Fid
	}
	return nil
}

func (x *InvalidateRequest) GetNewVersion() uint64 {
	if x != nil {
		return x.NewVersion
	}
	return 0
}

type InvalidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidateResponse) Reset() {
	*x = InvalidateResponse{}
	mi := &file_api_callback_callback_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateResponse) ProtoMessage() {}

func (x *InvalidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_callback_callback_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateResponse.ProtoReflect.Descriptor instead.
func (*InvalidateResponse) Descriptor() ([]byte, []int) {
	return file_api_callback_callback_proto_rawDescGZIP(), []int{1}
}

func (x *InvalidateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_callback_callback_proto protoreflect.FileDescriptor

const file_api_callback_callback_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/callback/callback.proto\x12\bcallback\x1a\x1fapi/fileserver/fileserver.proto\"W\n" +
	"\x11InvalidateRequest\x12!\n" +
	"\x03fid\x18\x01 \x01(\v2\x0f.fileserver.FIDR\x03fid\x12\x1f\n" +
	"\vnew_version\x18\x02 \x01(\x04R\n" +
	"newVersion\".\n" +
	"\x12InvalidateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2Y\n" +
	"\x0eClientCallback\x12G\n" +
	"\n" +
	"Invalidate\x12\x1b.callback.InvalidateRequest\x1a\x1c.callback.InvalidateResponseB-Z+github.com/umangshikarvar/dvfs/api/callbackb\x06proto3"

var (
	file_api_callback_callback_proto_rawDescOnce sync.Once
	file_api_callback_callback_proto_rawDescData []byte
)

func file_api_callback_callback_proto_rawDescGZIP() []byte {
	file_api_callback_callback_proto_rawDescOnce.Do(func() {
		file_api_callback_callback_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_callback_callback_proto_rawDesc), len(file_api_callback_callback_proto_rawDesc)))
	})
	return file_api_callback_callback_proto_rawDescData
}

var file_api_callback_callback_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_callback_callback_proto_goTypes = []any{
	(*InvalidateRequest)(nil),  // 0: callback.InvalidateRequest
	(*InvalidateResponse)(nil), // 1: callback.InvalidateResponse
	(*fileserver.FID)(nil),     // 2: fileserver.FID
}
var file_api_callback_callback_proto_depIdxs = []int32{
	2, // 0: callback.InvalidateRequest.fid:type_name -> fileserver.FID
	0, // 1: callback.ClientCallback.Invalidate:input_type -> callback.InvalidateRequest
	1, // 2: callback.ClientCallback.Invalidate:output_type -> callback.InvalidateResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_callback_callback_proto_init() }
func file_api_callback_callback_proto_init() {
	if File_api_callback_callback_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_callback_callback_proto_rawDesc), len(file_api_callback_callback_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_callback_callback_proto_goTypes,
		DependencyIndexes: file_api_callback_callback_proto_depIdxs,
		MessageInfos:      file_api_callback_callback_proto_msgTypes,
	}.Build()
	File_api_callback_callback_proto = out.File
	file_api_callback_callback_proto_goTypes = nil
	file_api_callback_callback_proto_depIdxs = nil
}
