// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: api/callback/callback.proto

package callback

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClientCallback_Invalidate_FullMethodName = "/callback.ClientCallback/Invalidate"
)

// ClientCallbackClient is the client API for ClientCallback service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ClientCallback service (runs on client)
type ClientCallbackClient interface {
	Invalidate(ctx context.Context, in *InvalidateRequest, opts ...grpc.CallOption) (*InvalidateResponse, error)
}

type clientCallbackClient struct {
	cc grpc.ClientConnInterface
}

func NewClientCallbackClient(cc grpc.ClientConnInterface) ClientCallbackClient {
	return &clientCallbackClient{cc}
}

func (c *clientCallbackClient) Invalidate(ctx context.Context, in *InvalidateRequest, opts ...grpc.CallOption) (*InvalidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvalidateResponse)
	err := c.cc.Invoke(ctx, ClientCallback_Invalidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientCallbackServer is the server API for ClientCallback service.
// All implementations must embed UnimplementedClientCallbackServer
// for forward compatibility.
//
// ClientCallback service (runs on client)
type ClientCallbackServer interface {
	Invalidate(context.Context, *InvalidateRequest) (*InvalidateResponse, error)
	mustEmbedUnimplementedClientCallbackServer()
}

// UnimplementedClientCallbackServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientCallbackServer struct{}

func (UnimplementedClientCallbackServer) Invalidate(context.Context, *InvalidateRequest) (*InvalidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Invalidate not implemented")
}
func (UnimplementedClientCallbackServer) mustEmbedUnimplementedClientCallbackServer() {}
func (UnimplementedClientCallbackServer) testEmbeddedByValue()                        {}

// UnsafeClientCallbackServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientCallbackServer will
// result in compilation errors.
type UnsafeClientCallbackServer interface {
	mustEmbedUnimplementedClientCallbackServer()
}

func RegisterClientCallbackServer(s grpc.ServiceRegistrar, srv ClientCallbackServer) {
	// If the following call panics, it indicates UnimplementedClientCallbackServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientCallback_ServiceDesc, srv)
}

func _ClientCallback_Invalidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvalidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientCallbackServer).Invalidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientCallback_Invalidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientCallbackServer).Invalidate(ctx, req.(*InvalidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientCallback_ServiceDesc is the grpc.ServiceDesc for ClientCallback service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientCallback_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "callback.ClientCallback",
	HandlerType: (*ClientCallbackServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invalidate",
			Handler:    _ClientCallback_Invalidate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/callback/callback.proto",
}
